import Head from 'next/head'
import Navbar from '../Navbar2'
import Footer from '../../pages/project/footer'
import styles from './Layout.module.scss'

export default function Layout(props) {
    return (
        <div className={styles.layout}>
            <Head>
                <title>My Last</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <Navbar />
            <Footer />
            <main className={styles.main}>{props.children}</main>
        </div>
    )
}
